// Built-in category definitions used by parser and DB seeding.
const List<Map<String, Object>> BUILTIN_CATEGORIES = [
  {'keywords': ['bonus anak', 'bonus anak sekolah', 'bonus'], 'category': 'Bonus Anak Sekolah', 'type': 'income'},
  {'keywords': ['gaji', 'tunjangan keluarga', 'tunjangan jf', 'tunjangan kinerja', 'tunjangan', 'uang makan', 'uang pertek', 'uang makan'], 'category': 'Gaji & Tunjangan', 'type': 'income'},
  {'keywords': ['thr'], 'category': 'THR', 'type': 'income'},
  {'keywords': ['kontrakan', 'sewa kontrakan', 'terima kontrakan'], 'category': 'Kontrakan', 'type': 'income'},
  {'keywords': ['uang bonus', 'bonus'], 'category': 'Uang Bonus', 'type': 'income'},

  {'keywords': ['saham', 'reksadana', 'deposito', 'obligasi', 'investasi', 'beli saham', 'beli reksadana', 'beli obligasi'], 'category': 'Investasi', 'type': 'investment'},

  {'keywords': ['bahan masak', 'bahan memasak', 'bahan masakan', 'bahan masak'], 'category': 'Bahan Memasak', 'type': 'expense'},
  {'keywords': ['bensin', 'bbm'], 'category': 'Bensin', 'type': 'expense'},
  {'keywords': ['beras'], 'category': 'Beras', 'type': 'expense'},
  {'keywords': ['biaya sekolah', 'uang sekolah', 'sekolah'], 'category': 'Biaya Sekolah', 'type': 'expense'},
  {'keywords': ['berobat', 'pengobatan', 'cek dokter', 'dokter'], 'category': 'Berobat/Pengobatan', 'type': 'expense'},
  {'keywords': ['buah'], 'category': 'Buah', 'type': 'expense'},
  {'keywords': ['cicilan'], 'category': 'Cicilan', 'type': 'expense'},
  {'keywords': ['eating out', 'makan diluar', 'makan'], 'category': 'Eating Out', 'type': 'expense'},
  {'keywords': ['galon'], 'category': 'Galon', 'type': 'expense'},
  {'keywords': ['gas'], 'category': 'Gas', 'type': 'expense'},
  {'keywords': ['gift', 'hadiah'], 'category': 'Gift', 'type': 'expense'},
  {'keywords': ['groceries', 'belanja'], 'category': 'Groceries', 'type': 'expense'},
  {'keywords': ['hiburan'], 'category': 'Hiburan', 'type': 'expense'},
  {'keywords': ['infaq'], 'category': 'Infaq', 'type': 'expense'},
  {'keywords': ['jajan'], 'category': 'Jajan', 'type': 'expense'},
  {'keywords': ['kontrakan bayar', 'bayar kontrakan'], 'category': 'Kontrakan', 'type': 'expense'},
  {'keywords': ['listrik'], 'category': 'Listrik', 'type': 'expense'},
  {'keywords': ['pakaian'], 'category': 'Pakaian', 'type': 'expense'},
  {'keywords': ['paket data', 'data', 'kuota'], 'category': 'Paket Data', 'type': 'expense'},
  {'keywords': ['pdam', 'air'], 'category': 'PDAM (AIR)', 'type': 'expense'},
  {'keywords': ['perbaikan rumah', 'perbaikan', 'perbaikan rumah'], 'category': 'Perbaikan Rumah', 'type': 'expense'},
  {'keywords': ['pampers'], 'category': 'Pampers', 'type': 'expense'},
  {'keywords': ['pulsa'], 'category': 'Pulsa', 'type': 'expense'},
  {'keywords': ['rekreasi'], 'category': 'Rekreasi', 'type': 'expense'},
  {'keywords': ['sampah'], 'category': 'Sampah', 'type': 'expense'},
  {'keywords': ['uang kuliah', 'kuliah'], 'category': 'Uang Kuliah', 'type': 'expense'},
  {'keywords': ['umroh', 'umroh biaya'], 'category': 'Umroh Biaya', 'type': 'expense'},
  {'keywords': ['zakat'], 'category': 'Zakat', 'type': 'expense'},
  {'keywords': ['lain-lain', 'lain lain', 'lainnya'], 'category': 'Lain-lain', 'type': 'expense'},

  {'keywords': ['dana darurat', 'tabungan darurat'], 'category': 'Dana Darurat', 'type': 'saving'},
  {'keywords': ['haji', 'biaya haji'], 'category': 'Haji', 'type': 'saving'},
  {'keywords': ['mobil'], 'category': 'Mobil', 'type': 'saving'},
  {'keywords': ['motor'], 'category': 'Motor', 'type': 'saving'},
  {'keywords': ['qurban'], 'category': 'Qurban', 'type': 'saving'},
  {'keywords': ['rumah'], 'category': 'Rumah', 'type': 'saving'},
  {'keywords': ['sepeda'], 'category': 'Sepeda', 'type': 'saving'},
  {'keywords': ['umroh tabungan', 'tabungan umroh'], 'category': 'Umroh', 'type': 'saving'},
  {'keywords': ['uang kuliah tabungan'], 'category': 'Uang Kuliah', 'type': 'saving'},
];
