-- Supabase schema migration for Catatan Keuangan Pintar
-- Jalankan via `supabase migration new` atau import manual di SQL editor.

-- Profiles
create table if not exists public.profiles (
  id uuid primary key references auth.users on delete cascade,
  display_name text,
  avatar_url text,
  preferred_currency text default 'IDR',
  locale text default 'id-ID',
  created_at timestamptz default now()
);

-- Conversations & participants
create table if not exists public.conversations (
  id uuid primary key default gen_random_uuid(),
  title text,
  owner_id uuid not null references public.profiles(id) on delete cascade,
  type text not null check (type in ('personal','household','business')),
  llm_preset text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.conversation_participants (
  conversation_id uuid references public.conversations(id) on delete cascade,
  user_id uuid references public.profiles(id) on delete cascade,
  role text not null check (role in ('owner','editor','viewer')),
  status text default 'active' check (status in ('active','invited','left')),
  joined_at timestamptz default now(),
  primary key (conversation_id, user_id)
);

-- Messages & delivery events
create table if not exists public.messages (
  id uuid primary key default gen_random_uuid(),
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  author_id uuid references public.profiles(id) on delete set null,
  text text,
  metadata jsonb default '{}'::jsonb,
  status text default 'sent' check (status in ('sent','delivered','read','failed')),
  created_at timestamptz default now()
);

create table if not exists public.message_events (
  id bigint generated by default as identity primary key,
  message_id uuid not null references public.messages(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  event_type text check (event_type in ('delivered','read')),
  event_ts timestamptz default now()
);

-- Categories
create table if not exists public.categories (
  id uuid primary key default gen_random_uuid(),
  conversation_id uuid references public.conversations(id) on delete cascade,
  name text not null,
  type text not null check (type in ('income','expense','saving','investment')),
  keywords text,
  icon text,
  is_builtin boolean default false,
  created_at timestamptz default now()
);

-- Transactions
create table if not exists public.transactions (
  id uuid primary key default gen_random_uuid(),
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  message_id uuid references public.messages(id) on delete set null,
  owner_id uuid references public.profiles(id) on delete set null,
  kind text not null check (kind in ('income','expense','saving_in','saving_out','investment_in','investment_out','transfer')),
  amount numeric(18,2) not null,
  currency text not null default 'IDR',
  category_id uuid references public.categories(id) on delete set null,
  description text,
  occurred_at timestamptz default now(),
  created_at timestamptz default now(),
  source text default 'chat',
  confidence numeric(5,2) default 1.0
);

create table if not exists public.transaction_items (
  id uuid primary key default gen_random_uuid(),
  transaction_id uuid not null references public.transactions(id) on delete cascade,
  label text,
  amount numeric(18,2)
);

-- Documents and LLM jobs
create table if not exists public.documents (
  id uuid primary key default gen_random_uuid(),
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  uploader_id uuid references public.profiles(id) on delete set null,
  message_id uuid references public.messages(id) on delete set null,
  file_url text not null,
  mime_type text,
  extracted_text text,
  llm_payload jsonb,
  status text default 'processing' check (status in ('processing','ready','failed')),
  created_at timestamptz default now()
);

create table if not exists public.llm_jobs (
  id bigint generated by default as identity primary key,
  conversation_id uuid not null,
  message_id uuid,
  document_id uuid,
  job_type text not null check (job_type in ('parse_chat','parse_document','reconcile')),
  payload jsonb not null,
  status text default 'queued' check (status in ('queued','running','error','done')),
  error text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Sync checkpoints per device
create table if not exists public.sync_states (
  device_id uuid,
  user_id uuid references public.profiles(id) on delete cascade,
  conversation_id uuid references public.conversations(id) on delete cascade,
  last_message_at timestamptz,
  checkpoint jsonb,
  primary key (device_id, conversation_id)
);

-- Audit log
create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  user_id uuid,
  action text,
  entity text,
  entity_id uuid,
  data jsonb,
  created_at timestamptz default now()
);

-- Indexes
create index if not exists messages_conversation_created_idx on public.messages (conversation_id, created_at desc);
create index if not exists transactions_conversation_occurred_idx on public.transactions (conversation_id, occurred_at desc);
create index if not exists documents_conversation_created_idx on public.documents (conversation_id, created_at desc);
create index if not exists llm_jobs_status_created_idx on public.llm_jobs (status, created_at);

-- Enable RLS
alter table public.conversations enable row level security;
alter table public.conversation_participants enable row level security;
alter table public.messages enable row level security;
alter table public.transactions enable row level security;
alter table public.categories enable row level security;
alter table public.documents enable row level security;
alter table public.sync_states enable row level security;

-- Policies
create policy if not exists "conversation access" on public.conversations
  for select using (
    auth.uid() = owner_id or
    auth.uid() in (
      select user_id from public.conversation_participants cp
      where cp.conversation_id = conversations.id and cp.status = 'active'
    )
  );

create policy if not exists "manage owned conversations" on public.conversations
  for all using (auth.uid() = owner_id);

create policy if not exists "participants read" on public.conversation_participants
  for select using (
    auth.uid() in (
      select user_id from public.conversation_participants cp
      where cp.conversation_id = conversation_participants.conversation_id and cp.status = 'active'
    )
  );

create policy if not exists "owner manage participants" on public.conversation_participants
  for all using (
    auth.uid() in (
      select owner_id from public.conversations c
      where c.id = conversation_participants.conversation_id
    )
  );

create policy if not exists "participating messages" on public.messages
  for select using (
    auth.uid() in (
      select user_id from public.conversation_participants cp
      where cp.conversation_id = messages.conversation_id and cp.status = 'active'
    )
  );

create policy if not exists "author can insert" on public.messages
  for insert with check (
    auth.uid() = author_id and
    auth.uid() in (
      select user_id from public.conversation_participants cp
      where cp.conversation_id = messages.conversation_id and cp.status = 'active'
    )
  );

create policy if not exists "editors write transactions" on public.transactions
  for insert with check (
    auth.uid() in (
      select user_id from public.conversation_participants cp
      where cp.conversation_id = transactions.conversation_id
        and cp.role in ('owner','editor')
        and cp.status = 'active'
    )
  );

create policy if not exists "read transactions" on public.transactions
  for select using (
    auth.uid() in (
      select user_id from public.conversation_participants cp
      where cp.conversation_id = transactions.conversation_id and cp.status = 'active'
    )
  );

create policy if not exists "category visibility" on public.categories
  for select using (
    conversation_id is null or
    auth.uid() in (
      select user_id from public.conversation_participants cp
      where cp.conversation_id = categories.conversation_id and cp.status = 'active'
    )
  );

create policy if not exists "category maintainers" on public.categories
  for insert with check (
    conversation_id is null or
    auth.uid() in (
      select user_id from public.conversation_participants cp
      where cp.conversation_id = categories.conversation_id and cp.role in ('owner','editor') and cp.status = 'active'
    )
  );

create policy if not exists "documents read" on public.documents
  for select using (
    auth.uid() in (
      select user_id from public.conversation_participants cp
      where cp.conversation_id = documents.conversation_id and cp.status = 'active'
    )
  );

create policy if not exists "sync states owner" on public.sync_states
  for all using (auth.uid() = user_id);

-- TODO: tambah policy spesifik untuk update status message_events dan llm_jobs via service-role.
